export class Family {
    fname : any;
    faadhaar : any;
    fmobile : any;
    foccupation : any;
    faddress : any;
    fqualification : any;
    fpan : any;
    ftax : any;
    femail : any;
    mname : any;
    maadhaar : any;
    mmobile : any;
    moccupation : any;
    maddress : any;
    mqualification : any;
    mpan : any;
    mtax : any;
    memail : any;
    unclean : any;
    income : any;
    bpl : any;
    certificate_no :any;
    issuing : any;
    idate : any;
    sname : any;
    sclass : any;
    srn : any;
    relation : any;
}
